### ISSUE TITLE
Build failure on Mirage Skeleton unikernels due to missing Zarith

### ISSUE THREAD

**Issue by nickrobison** [RyanGibb/hillingar#13]
While trying to use Hillingar to build a personal Mirage project, I ran into an issue with `mirage-crypto` failing to build due to missing `zarith` library. Here's the full stack trace:

```
error: builder for '/nix/store/0bqbv7r56k8jvqx95vpz18y56gjicaxj-http-fetch-dev.drv' failed with exit code 1;
       last 18 log lines:
       > unpacking sources
       > unpacking source archive /nix/store/j1rcjp30l112minzk1wqyh9r9pia9bai-3x9vch4pay7082gpg0kjp0jx4r873sjs-configured-src
       > source root is 3x9vch4pay7082gpg0kjp0jx4r873sjs-configured-src
       > preBuild
       > building
       > File "duniverse/mirage-crypto/pk/dune", line 4, characters 20-26:
       > 4 |  (libraries cstruct zarith mirage-crypto mirage-crypto-rng sexplib0 eqaf.cstruct)
       >                         ^^^^^^
       > Error: Library "zarith" not found.
       > -> required by library "mirage-crypto-pk" in
       >    _build/default/duniverse/mirage-crypto/pk
       > -> required by executable main in device-usage/http-fetch/dune.build:13
       > -> required by _build/default/device-usage/http-fetch/main.exe
       > -> required by _build/default/device-usage/http-fetch/http-fetch
       > -> required by _build/default/device-usage/http-fetch/dist/http-fetch
       > -> required by alias device-usage/http-fetch/dist/all
       > -> required by alias device-usage/http-fetch/dist/default
       >
```

I was able to repo this using the mirage skeleton repo using the `device-usage/http-fetch` example, which only depends on cohttp. This occurs with Mirage 4.5.0 (due to the change in arg handling) on both Ocaml 4.14.1 and Ocaml 5.1.1. The same unikernel builds via traditional opam methods, but it's totally possible I'm missing something simple.

Happy to provide any additional information, as I'm sure my initial report isn't very helpful.

Thanks for an awesome project, I'm really excited to use it more!

**Comment by RyanGibb** [comment]
Hi @nickrobison, any chance you could share the repository that I can use to reproduce the issue?

**Comment by RyanGibb** [comment]
This is due to the fact that Zarith doesn't support building with dune and we're not picking up the overlay in https://github.com/dune-universe/opam-overlays/tree/master/packages/zarith. Specifying `zarith = "1.12+dune";` picks up this overlay. 
See https://github.com/RyanGibb/hillingar/issues/3#issuecomment-1268271304 for more details.

However, it looks like `1.12+dune` fails to build in Nix at [this line](https://github.com/dune-universe/Zarith/blob/82de3e1782cd3bec6c66e85e9dfc9a2764513044/dune#L31) dune to some [hardcoded](https://github.com/dune-universe/Zarith/commit/82de3e1782cd3bec6c66e85e9dfc9a2764513044#diff-0e2559ac93e2453ea3333c936a393b90e35991f5aaa7a5b90de242fd9ce6b824) discovery. This either needs to be fixed upstream or patched here.

**Comment by RyanGibb** [comment]
Ah, it looks like mirage-opam-overlays has a version `zarith.1.13+dune+mirage` which works https://github.com/dune-universe/opam-overlays/issues/196#issuecomment-2025431090

I've pushed a commit updating the version of this repository used by hillingar and now we can build http-fetch with:
```
{
  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs";
    hillingar.url = "github:RyanGibb/hillingar";
  };

  outputs = { self, nixpkgs, flake-utils, hillingar, ... }:
    flake-utils.lib.eachDefaultSystem (system:
      let pkgs = nixpkgs.legacyPackages.${system}; in {
        packages = let
          mirage-nix = (hillingar.lib.${system});
          inherit (mirage-nix) mkUnikernelPackages;
        in
          mkUnikernelPackages {
            unikernelName = "http-fetch";
            depexts = with pkgs; [ gmp ];
            monorepoQuery = {
              zarith = "1.13+dune+mirage";
            };
            query = {
              ocaml-base-compiler = "*";
              mirage = "4.5.0";
            };
          } self;

        defaultPackage = self.packages.${system}.unix;
      }
    );
}
```

**Comment by RyanGibb** [comment]
Let me know if this works for your project too!

**Comment by nickrobison** [comment]
Works great! Thanks for the quick response to this!

**Comment by RyanGibb** [comment]
No problem!
